version: '3'

services:
  app:
    container_name: forge
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      net:
        ipv4_address: 172.28.0.3
  
  db:
    image: mongo
    container_name: mongo
    networks:
      net:
        ipv4_address: 172.28.0.2

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16