version: '3'

services:
  app:
    container_name: app
    build: .
    environment:
      - DB_HOST=172.28.0.2
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      net:
        ipv4_address: 172.28.0.3
  
  db:
    container_name: db
    build: dockerfiles/db/.
    networks:
      net:
        ipv4_address: 172.28.0.2

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16